<h1>Détails de la commande</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Produit</th>
            <th>Prix unitaire</th>
            <th>Quantité commandée</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($details as $detail): ?>
            <tr>
                <td><?= $detail['productName'] ?></td>
                <td><?= number_format($detail['priceEach'], 2, ',', ' ') ?>€</td>
                <td><?= $detail['quantityOrdered'] ?></td>
                <td><?= number_format($detail['totalDetail'], 2, ',', ' ') ?>€</td>
            </tr>
        <?php endforeach ?>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="3">Total de la commande</th>
            <th><?= number_format($total, 2, ',', ' ') ?>€</th>
        </tr>
    </tfoot>
</table>