<h1>Détail de l'employé numéro <?= $employee['employeeNumber'] ?></h1>

<dl>
    <dt>Numéro</dt>
    <dd><?= $employee['employeeNumber'] ?></dd>
    <dt>Prénom</dt>
    <dd><?= $employee['firstName'] ?></dd>
    <dt>Nom</dt>
    <dd><?= $employee['lastName'] ?></dd>
    <dt>Email</dt>
    <dd><?= $employee['email'] ?></dd>
    <dt>Bureau</dt>
    <dd><?= $employee['city'] ?></dd>
    <dt>Fonction</dt>
    <dd><?= $employee['jobTitle'] ?></dd>
    <dt>Manager</dt>
    <dd><?= $employee['managerFirstName'] ?> <?= $employee['managerLastName'] ?></dd>
    <dt>Extension</dt>
    <dd><?= $employee['extension'] ?></dd>
</dl>