<!-- Fichier contenant le html commun à toutes les pages -->
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Liste des employés</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="index.php">Gestion de l'entreprise</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="index.php">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="?page=employee-list">Liste des employés</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="?page=customer-list">Liste des clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="?page=order-list">Liste des commandes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        <!-- Partie spécifique à une page (liste des employés, détail d'un employé, accueil...) -->
        <!-- La variable $template contiendra le nom du template à charger (variable qui doit être définie dans toutes les pages) -->
        <?php require $template ?>
    </main>
</body>
</html>